spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
#      ddl-auto: validate

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: test_user
    password: test_user
    driver-class-name: oracle.jdbc.OracleDriver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
